Set arg x for xklb db path
iiab/calibre-web pull request #249
Opened 2024-09-12 14:40 UTC by deldesir

2024-09-12 16:34 UTC, avni requested changes
Added a comment to explain the addition of the config param.

2024-09-12 16:34 UTC, avni commented on cps/cli.py
> +        parser.add_argument('-x', metavar='path', help='path and name to xklb db')
```suggestion
        # this set of changes adds a new config parameter for the experimental xklb.db file to be used by lb wrapper and makes the path available in the Calibre-Web template: https://github.com/iiab/iiab/blob/master/roles/calibre-web/templates/calibre-web.service.j2
        parser.add_argument('-x', metavar='path', help='path and name to xklb db')
```

2024-09-12 18:56 UTC, holta commented
Is this PR truly needed, and if so why?

- "Parameter Pollution" (i.e. soft-coding of variables / flags / options prior to a proven need) is so often tempting but... far too often creates maintenance burdens down the road... _rather than helping a broad demographic?_

- Conversely, if the need for another parameter is in fact very real, for a specific QA/Community demographic or any other, then let's please all help articulate that in coming days.  (Either Way!)  And if the need is confirmed truly real — let's explain why parametrization is genuinely necessary here (e.g. justifying the inevitable ~ additional maintenance/testing/security burdens) ~ _ensuring we avoid Complexity Bloat..._

> [Premature Generalization, like...] Premature Optimization is the Root of All Evil
> —Donald Knuth (1974)

2024-09-25 01:46 UTC, deldesir commented
Parametrization is not necessary nor needed. KISS principle.

2024-09-25 01:46 UTC, closed without merging