Suggested improvements for scripts/lb-wrapper
iiab/calibre-web pull request #87
Opened 2024-01-10 06:16 UTC by holta

An executive decision was made to replace PR #86 with smaller PR's.  Hopefully this (or similar) is one of those PR's.

This PR was tested on a Ubuntu 24.04 pre-release VM.  And is already getting too large.

Thanks @deldesir and @EMG70 for reviewing.  I think is good enough until @deldesir and others improve on it later.  But LMK your thoughts, with any clarifications that are needed.

<details>
  <summary>Example output</summary>

```
root@box:~# lb-wrapper https://youtu.be/2oMXIbOiASI
/usr/local/bin/lb
2024-01-10 01:12:03 - [Info] xklb version: 2.3.011
2024-01-10 01:12:03 - [Info] Old /library/downloads/calibre-web/survey.db moved aside.
2024-01-10 01:12:03 - [Info] Running xklb commands: lb tubeadd /library/downloads/calibre-web/survey.db https://youtu.be/2oMXIbOiASI -vv && lb dl /library/downloads/calibre-web/survey.db --prefix /library/downloads/calibre-web --video https://youtu.be/2oMXIbOiASI --format best --format-sort 'tbr~1000' --write-thumbnail -vv
2024-01-10 01:12:03 - [Error] library v2.3.011
2024-01-10 01:12:03 - [Error] ['/usr/local/bin/lb', 'tubeadd', '/library/downloads/calibre-web/survey.db', 'https://youtu.be/2oMXIbOiASI', '-vv']
2024-01-10 01:12:03 - [Error] {'extractor_config': {}, 'download_archive': '~/.local/share/yt_archive.txt', 'extra_media_data': {}, 'extra_playlist_data': {}, 'verbose': 2, 'db': <Database <sqlite3.Connection object at 0x7e99597d4400>>, 'database': '/library/downloads/calibre-web/survey.db', 'playlists': ['https://youtu.be/2oMXIbOiASI'], 'action': 'tubeadd'}
2024-01-10 01:12:03 - [Error] {'noprogress': True, 'skip_download': True, 'lazy_playlist': True, 'extract_flat': True, 'no_check_certificate': True, 'ignore_no_formats_error': True, 'skip_playlist_after_errors': 21, 'playlistend': 20000}
2024-01-10 01:12:04 - [Error] yt-dlp initialized 0.0635
2024-01-10 01:12:04 - [Info] [youtube] Extracting URL: https://youtu.be/2oMXIbOiASI
2024-01-10 01:12:04 - [Info] [youtube] 2oMXIbOiASI: Downloading webpage
2024-01-10 01:12:04 - [Info] [youtube] 2oMXIbOiASI: Downloading ios player API JSON
2024-01-10 01:12:04 - [Info] [youtube] 2oMXIbOiASI: Downloading android player API JSON
2024-01-10 01:12:04 - [Error] no such table: media
2024-01-10 01:12:04 - [Error] Importing playlist-less media https://youtu.be/2oMXIbOiASI
2024-01-10 01:12:05 - [Error] media.playlist_media_add 0.8982
2024-01-10 01:12:05 - [Error] ydl.extract_info done 0.0412
2024-01-10 01:12:05 - [Error]
2024-01-10 01:12:05 - [Error] Optimizing database
2024-01-10 01:12:05 - [Error] Processing table: media
2024-01-10 01:12:05 - [Error] Transforming column order: ['id', 'size', 'duration', 'time_uploaded', 'time_created', 'time_modified', 'time_deleted', 'time_downloaded', 'fps', 'view_count', 'path', 'webpath', 'extractor_id']
2024-01-10 01:12:05 - [Error] Creating index: id
2024-01-10 01:12:05 - [Error] Creating index: size
2024-01-10 01:12:05 - [Error] Creating index: duration
2024-01-10 01:12:05 - [Error] Creating index: time_uploaded
2024-01-10 01:12:05 - [Error] Creating index: time_created
2024-01-10 01:12:05 - [Error] Creating index: time_modified
2024-01-10 01:12:05 - [Error] Creating index: time_deleted
2024-01-10 01:12:05 - [Error] Creating index: time_downloaded
2024-01-10 01:12:05 - [Error] Creating index: fps
2024-01-10 01:12:05 - [Error] Creating index: view_count
2024-01-10 01:12:05 - [Error] Creating index: live_status
2024-01-10 01:12:05 - [Error] Creating index: path
2024-01-10 01:12:05 - [Error] Creating index: webpath
2024-01-10 01:12:05 - [Error] Creating index: uploader
2024-01-10 01:12:05 - [Error] Creating fts index: ['path', 'title']
2024-01-10 01:12:05 - [Error] Processing table: captions
2024-01-10 01:12:05 - [Error] Creating index: media_id
2024-01-10 01:12:05 - [Error] Creating index: time
2024-01-10 01:12:05 - [Error] Creating fts index: ['text']
2024-01-10 01:12:05 - [Error] Running VACUUM
2024-01-10 01:12:05 - [Error] Running ANALYZE
2024-01-10 01:12:05 - [Info]
2024-01-10 01:12:06 - [Error] library v2.3.011
2024-01-10 01:12:06 - [Error] ['/usr/local/bin/lb', 'dl', '/library/downloads/calibre-web/survey.db', '--prefix', '/library/downloads/calibre-web', '--video', 'https://youtu.be/2oMXIbOiASI', '--format', 'best', '--format-sort', 'tbr~1000', '--write-thumbnail', '-vv']
2024-01-10 01:12:06 - [Error] {'profile': 'video', 'extractor_config': {}, 'extra_media_data': {}, 'extra_playlist_data': {}, 'prefix': '/library/downloads/calibre-web', 'sort': 'm.path like "http%"\n        , m.title IS NOT NULL desc\n        , m.path\n        , random()', 'where': [], 'include': [], 'exclude': [], 'limit': 7200, 'retry_delay': '14 days', 'db': <Database <sqlite3.Connection object at 0x7efc3e5fee30>>, 'verbose': 2, 'database': '/library/downloads/calibre-web/survey.db', 'playlists': ['https://youtu.be/2oMXIbOiASI'], 'defaults': ['sort', 'limit'], 'unk': ['--format', 'best', '--format-sort', 'tbr~1000', '--write-thumbnail'], 'action': 'download'}
2024-01-10 01:12:06 - [Error] None
2024-01-10 01:12:06 - [Error] {'path': 'https://www.youtube.com/watch?v=2oMXIbOiASI', 'title': "Ice Cold Killers (Full Episode) | World's Deadliest", 'duration': 2664, 'time_created': 1704867124, 'size': 0, 'time_modified': 0, 'time_downloaded': 0, 'time_deleted': 0, 'extractor_key': 'Playlist-less media'}
2024-01-10 01:12:06 - [Error] {'noprogress': True, 'lazy_playlist': True, 'noplaylist': True, 'no_check_certificate': True, 'ignore_no_formats_error': True, 'skip_playlist_after_errors': 21, 'playlistend': 20000, 'extractor_args': {'youtube': {'skip': ['authcheck']}}, 'logger': <xklb.tube_backend.download.<locals>.DictLogger object at 0x7efc3e4b6f90>, 'postprocessors': [{'key': 'FFmpegMetadata'}, {'key': 'FFmpegEmbedSubtitle'}], 'restrictfilenames': True, 'playlist_items': '1', 'extractor_retries': 3, 'retries': 12, 'retry_sleep_functions': {'extractor': <function download.<locals>.<lambda> at 0x7efc3d8e7d80>, 'http': <function download.<locals>.<lambda> at 0x7efc3d8e7e20>, 'fragment': <function download.<locals>.<lambda> at 0x7efc3d8e7ec0>}, 'outtmpl': {'default': '/library/downloads/calibre-web/%(extractor_key,extractor)s/%(uploader,uploader_id)s/%(title).200B_%(view_count)3.2D_[%(id).60B].%(ext)s', 'chapter': '/library/downloads/calibre-web/%(extractor_key,extractor)s/%(uploader,uploader_id)s/%(title).200B_%(section_number)03d_%(section_title)s_%(view_count)3.2D_[%(id).60B].%(ext)s'}, 'progress_hooks': [<function download.<locals>.<lambda> at 0x7efc3d8e7f60>], 'subtitlesformat': 'srt/best', 'format': 'best', 'format_sort': ['tbr~1000'], 'writethumbnail': True, '_warnings': ['"-f best" selects the best pre-merged format which is often not the best option.\n         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.\n         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning']}
downloading   0.0%  838.86KiB/s
downloading   0.0%  997.14KiB/s
downloading   0.0%    1.29MiB/s
downloading   0.0%    1.95MiB/s
downloading   0.0%    3.24MiB/s
downloading   0.0%    5.30MiB/s
downloading   0.0%    7.82MiB/s
downloading   0.1%    8.81MiB/s
downloading   0.2%   10.02MiB/s
downloading   0.4%   11.27MiB/s
downloading   0.7%   12.33MiB/s
downloading   1.5%   15.74MiB/s
downloading   2.9%   23.04MiB/s
downloading   3.6%   25.28MiB/s
downloading   3.6%  Unknown B/s
downloading   3.6%    1.70MiB/s
downloading   3.6%    2.17MiB/s
downloading   3.6%    3.11MiB/s
downloading   3.6%    5.06MiB/s
downloading   3.6%    8.40MiB/s
downloading   3.6%   11.45MiB/s
downloading   3.7%   13.29MiB/s
downloading   3.7%   17.95MiB/s
downloading   3.9%   22.60MiB/s
downloading   4.3%   30.11MiB/s
downloading   5.0%   39.73MiB/s
downloading   6.5%   45.44MiB/s
downloading   7.1%   50.00MiB/s
downloading   7.1%  Unknown B/s
downloading   7.1%  Unknown B/s
downloading   7.1%    4.12MiB/s
downloading   7.1%    5.33MiB/s
downloading   7.1%    7.92MiB/s
downloading   7.1%    7.22MiB/s
 [...]

2024-01-10 06:23 UTC, holta commented
Example test results — after running the same/above test using the "Download to IIAB" button:

```
root@box:~# tree -h /library/calibre-web/
[4.0K]  /library/calibre-web/
├── [4.0K]  Nat Geo WILD
│   └── [4.0K]  Ice Cold Killers (Full Episode) , World's Deadliest (1)
│       ├── [274M]  Ice Cold Killers (Full Episode) , World's - Nat Geo WILD.mp4
│       └── [ 66K]  cover.jpg
├── [4.0K]  config
│   └── [124K]  app.db
├── [340K]  metadata.db
└── [ 13K]  metadata_db_prefs_backup.json

4 directories, 5 files
```

2024-01-10 06:29 UTC, holta commented
Just FYI this PR also:

- Changes `scripts/lb-wrapper` chmod permissions from 100644 → 100755 (might as well make it executable out-of-the-box, for easier CLI rapid-testing etc).
- Deletes `scripts/lb-wrapper.greedy` in favor of Lines 10-12 near the top of scripts/lb-wrapper here:

```
# Or download largest possible HD-style / UltraHD videos, to try to force
# out-of-memory "502 Bad Gateway" for testing of issues like #37 and #79
# FORMAT_OPTIONS="--format-sort size"
```

2024-01-10 11:42 UTC, deldesir reviewed
Looks good to me.

2024-01-10 12:20 UTC, deldesir commented on scripts/lb-wrapper
> +    log "Error" "Error $rc occurred while running lb-wrapper's xklb commands."
Good you log the return code here.

2024-01-10 12:39 UTC, deldesir commented on scripts/lb-wrapper
> +    if [[ $message =~ ^downloading* ]]; then
What about using `[[ $message == *"downloading"* ]]` for simplicity, as it efficiently checks for the presence of 'downloading' in the string, avoiding the overhead of regex?

2024-01-10 12:58 UTC, deldesir requested changes

2024-01-10 13:26 UTC, holta commented
@deldesir can you confirm the 50+ "Errors" (pasted in "Example output" above) are ugly-but-acceptable for now?

i.e. giving more visibility to these minor errors from xklb and yt-dlp and FFmpeg etc is the central purpose of this PR:

➡️ But should we perhaps label Line 64 as "Warning" ⚠️ instead of "Error" ?  So that words like "error" and "Error" are _reserved for more seriously urgent problems_ within our logs / logging?

2024-01-10 13:35 UTC, holta commented on scripts/lb-wrapper
> +     2> >(while read -r line; do log "Error" "$line" 1>&2; done) &
```suggestion
     2> >(while read -r line; do log "Warning" "$line" 1>&2; done) &
```

2024-01-10 13:41 UTC, deldesir commented
> Thanks @deldesir and @EMG70 for reviewing. I think it's good enough until @deldesir and others improve on it later. But LMK your thoughts, with any questions/clarifications that are needed.
> Example output

You should have noticed a couple of messages in the output that are tagged as errors, but they are related to the normal xklb execution. These messages shouldn't impact the functionality of lb-wrapper; they are just part of the informative output of xklb printed in STDERR instead of STDOUT.

2024-01-10 14:00 UTC, deldesir approved these changes
Looks good so far.

2024-01-10 14:08 UTC, holta commented
Good Enough: PR #86 introduced most of the ideas here (let's give credit!) but grew somewhat too large to understand.

@deldesir and @emg70 please put additional recommendations in new tickets or PR's to further improve on lb-wrapper ✅

So we keep TDD momentum with regular, small, clearly explained PR's, Thank You!

ASIDE: This PR #87 can also serve to gently push us all to do the Earnest Hard Work of breaking apart larger ideas (large PR's) into smaller ideas (small PR's) — in order to build a **Stronger Collaboration Culture** upholding IIAB communities in all countries:

> _"Programs must be written for people to read and only incidentally for machines to execute."_ —Hal Abelson, circa 1984

2024-01-10 14:09 UTC, merged

2024-01-11 19:46 UTC, holta commented
> ➡️ But should we perhaps relabel Line 64 with `log "Warning" $line` ⚠️ instead of `log "Error" $line` ? So that words like "error" and "Error" are _reserved for more seriously urgent problems_ within our logs / logging?

Some prefer the word "Debug" as it's shorter than "Warning" and somewhat more precise!

Either if fine for me, but brevity's better possibly?

@deldesir and @avni: do you have a preference?

2024-01-11 20:04 UTC, deldesir commented
"Debug" aligns more with them. They are informative messages.

2024-01-12 10:56 UTC, holta commented
> "Debug" aligns more with them IMHO. They are informative messages.

Done!  As part this separate PR:

- PR #93

2024-02-26 03:57 UTC, avni commented
Sorry for missing this earlier, 

> > ➡️ But should we perhaps relabel Line 64 with `log "Warning" $line` ⚠️ instead of `log "Error" $line` ? So that words like "error" and "Error" are _reserved for more seriously urgent problems_ within our logs / logging?
> 
> Some prefer the word "Debug" as it's shorter than "Warning" and somewhat more precise!
> 
> Either is fine for me, but brevity's better possibly?
> 
> @deldesir and @avni: do you have a preference?

Agree that error seems to be a misnomer here and should be reserved for more urgent problems. Since this is only for informative purposes, I agree with @deldesir that "Debug" makes sense. "Warning" would be used for something wasn't working as expected, imo.